events {
    worker_connections 1024;
}
http {
    server_tokens off;
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;
    proxy_hide_header X-Powered-By;
    proxy_hide_header Server;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Frame-Options "DENY" always;

    server {
        listen 80;
        server_name hiraokaservices.lat www.hiraokaservices.lat;
        location / { return 301 https://$host$request_uri; }
    }

    server {
        listen 443 ssl;
        server_name hiraokaservices.lat www.hiraokaservices.lat;
        ssl_certificate     /etc/letsencrypt/live/hiraokaservices.lat/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/hiraokaservices.lat/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $api_gateway http://api-gateway:3000;

        location /admin  { proxy_pass http://api-gateway:3000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
        location /agente { proxy_pass http://api-gateway:3000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
        location /taller { proxy_pass http://api-gateway:3000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
        location / { proxy_pass $api_gateway; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
    }
}